# Only the ScalaTest tests will be run!
# The scripted tests require Docker which travis does not support
language: scala
scala:
  - 2.10.4
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_install:
  # Workaround for buffer overflow error in OpenJDK 7
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
